[package]
name = "me3-launcher"
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
description = "Launcher for me3"

[features]
sentry = ["dep:sentry"]
default = ["sentry"]

[dependencies]
stable-eyre = { version = "0.2" }
crash-context.workspace = true
eyre = "0.6"
dll-syringe.workspace = true
ipc-channel.workspace = true
me3-launcher-attach-protocol.workspace = true
me3-mod-protocol.workspace = true
minidump-writer = "0.10"
tracing-appender = "0.2"
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
sentry = { version = "0.38.1", optional = true }
normpath = "1.3.0"
tracing-core = "0.1.33"
toml.workspace = true
libc = "0.2.172"
me3_telemetry = { version = "0.2.0", path = "../telemetry" }

[lints]
workspace = true
