[package]
edition = "2021"
name = "launcher"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
color-eyre = { version = "0.6", features = ["issue-url"] }
eyre = "0.6"
iced-x86 = { version = "1", features = ["code_asm"] }
dll-syringe = "0.15"
me3-launcher-attach-protocol.workspace = true
tracing-error = "0.2"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = "0.1"
clap = { version = "4.5.4", features = ["derive", "env"] }

[dependencies.goblin]
version = "0.8"

[dependencies.windows-sys]
version = "0.52"
features = [
  "Wdk_System_Threading",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemInformation",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Memory",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Kernel",
]
