[package]
name = "me3-launcher"
version.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
stable-eyre = { version = "0.2" }
crash-context.workspace = true
eyre = "0.6"
dll-syringe.workspace = true
ipc-channel.workspace = true
me3-launcher-attach-protocol.workspace = true
me3-mod-protocol.workspace = true
minidumper.workspace = true
minidump-writer = "0.10"
tracing-appender = "0.2"
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
clap = { version = "4.5.4", features = ["derive", "env"] }

[lints]
workspace = true
