[package]
name = "me3-launcher"
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
description = "Launcher for me3"

[features]
sentry = ["me3_telemetry/sentry", "dep:sentry"]
default = []

[dependencies]
crash-context.workspace = true
eyre = { version = "0.6", default-features = false, features = [
    "track-caller",
] }
dll-syringe.workspace = true
ipc-channel.workspace = true
me3-launcher-attach-protocol.workspace = true
me3-mod-protocol.workspace = true
minidump-writer = "0.10"
tracing.workspace = true
sentry = { version = "0.38.1", optional = true }
toml.workspace = true
me3_telemetry = { path = "../telemetry" }
me3-env = { version = "0.5.0", path = "../env" }

[lints]
workspace = true
