[package]
name = "me3-mod-protocol"
edition = "2021"
version.workspace = true
repository.workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
topological-sort = "0.2.2"

[lints]
workspace = true