version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs
      - pip install mkdocs-material
      - pip install mkdocs-git-revision-date-localized-plugin
      - pip install mkdocs-git-authors-plugin
mkdocs:
  configuration: mkdocs.yml