# Define the site name
site_name: me3

# Set the site URL by using a Read the Docs environment variable:
# https://docs.readthedocs.io/en/stable/reference/environment-variables.html
# site_url: !ENV READTHEDOCS_CANONICAL_URL

# Set the Material for MkDocs theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - search.highlight
    - search.suggest
    - search.share
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
    scheme: slate
  # https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: docs/overrides
repo_url: https://github.com/garyttierney/me3
edit_uri: edit/docs/docs/
# Include extra JS to setup Read the Docs addons integrations
extra_javascript:
  - javascripts/readthedocs.js

nav:
  - Home: index.md
  - Blog:
    - blog/index.md


plugins:
  - blog
  - offline
  - meta
  - search