[package]
name = "me3-mod-host-watchdog"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
minidumper = "0.8"

[lints]
workspace = true
