[package]
name = "me3-mod-host"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
dynasmrt = "2"
dll-syringe = { workspace = true, features = ["payload-utils"] }
iced-x86 = "1.21.0"
me3-mod-protocol.workspace = true
me3-launcher-attach-protocol.workspace = true
retour = { git = "https://github.com/Hpmason/retour-rs", features = ["static-detour"] }
windows = { version = "0.54", features = [
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_System_SystemInformation",
] }
