[package]
name = "me3-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "me3"
path = "src/main.rs"

[features]
default = []
sentry = ["me3_telemetry/sentry"]

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
color-eyre = { version = "0.6.4" }
config = "0.15.11"
ctrlc = "3.4.7"
directories = "6.0.0"
is-terminal = "0.4.16"
me3-launcher-attach-protocol.workspace = true
me3-mod-protocol.workspace = true
me3_telemetry = { version = "0.2.0", path = "../telemetry" }
normpath = "1.3.0"
serde = { workspace = true, features = ["derive"] }
steamlocate = "2.0.1"
tempfile = "3.20.0"
toml.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[lints]
workspace = true
