[package]
name = "me3-launcher-attach-protocol"
edition = "2021"
version.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
me3-mod-protocol.workspace = true
serde.workspace = true
serde_derive.workspace = true

[lints]
workspace = true