[package]
name = "me3-launcher-attach-protocol"
version = "0.1.0"
edition = "2021"
vesion.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
me3-mod-protocol.workspace = true
serde.workspace = true
serde_derive.workspace = true