[package]
name = "me3-binary-analysis"
version = "0.6.1"
repository.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
pelite.workspace = true
rayon.workspace = true
thiserror.workspace = true
undname = "2.1"

[lints]
workspace = true
