[package]
name = "me3_telemetry"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
sentry = ["dep:sentry"]
default = ["sentry"]

[dependencies]
sentry = { version = "0.38.1", features = ["tracing"], optional = true }
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true

[lints]
workspace = true
