[package]
name = "me3_telemetry"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
sentry = ["dep:sentry"]
default = ["sentry"]

[dependencies]

tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
regex = { version = "1.11.1", features = ["unicode-case"] }
tracing-appender = "0.2.3"
tracing-opentelemetry = "0.30.0"
sentry-opentelemetry = "0.38.1"
opentelemetry = { version = "0.29", features = ["trace", "metrics"] }
opentelemetry-appender-tracing = { version = "0.29", features = [
    "tracing-opentelemetry",
    "experimental_metadata_attributes",
    "experimental_use_tracing_span_context",
] }
opentelemetry_sdk = { version = "0.29", default-features = false, features = [
    "trace",
    "rt-tokio",
    "experimental_trace_batch_span_processor_with_async_runtime",
    "experimental_logs_batch_log_processor_with_async_runtime",
] }
opentelemetry-otlp = { version = "0.29", default-features = false, features = [
    "trace",
    "logs",
    "http-proto",
    "reqwest-client",
] }
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }

[dependencies.sentry]
version = "0.38"
default-features = false
features = [
    "tracing",
    "backtrace",
    "contexts",
    "debug-images",
    "panic",
    "reqwest",
    "rustls",
]
optional = true
[lints]
workspace = true
