name: Changelog Check
on:
  pull_request:
    branches: [main]
    types:
      - labeled
      - synchronize
      - unlabeled

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10
  CLICOLOR: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Check if CHANGELOG.md is updated
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Check for CHANGELOG update
        shell: bash
        run: |
          if ! git diff --name-only -r ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha}} | grep 'CHANGELOG.md'; then
              echo "Changelog needs updated"
              exit 1
          fi
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
