name: Checks
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_if_config_schema_up_to_date:
    name: Check if config schema is up to date
    runs-on: windows-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Run | Generate Schema
        run: cargo run --locked --package me3-mod-protocol --bin schema > schemas/mod-profile.json

      - name: Check | Detect Changes
        uses: reviewdog/action-suggester@v1.21.0
        with:
          tool_name: me3-mod-protocol schema
          filter_mode: nofilter

  changelog:
    runs-on: ubuntu-latest
    name: Check if CHANGELOG.md is updated
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for CHANGELOG update
        shell: bash
        run: |
          if ! git diff --name-only -r ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha}} | grep 'CHANGELOG.md'; then
              echo "Changelog needs updated"
              exit 1
          fi
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}

  clippy:
    name: Clippy
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc
          components: clippy

      - uses: taiki-e/install-action@v2
        with:
          tool: clippy-sarif, sarif-fmt
      - run: cargo clippy --workspace --all-targets --all-features --message-format=json -- -Aunused | clippy-sarif | tee results.sarif | sarif-fmt
        shell: bash

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  fmt:
    name: Formatting
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          targets: x86_64-pc-windows-msvc
      - run: cargo +nightly fmt --all --check
