on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc
      - uses: ./.github/actions/setup-windows-toolchain
        if: matrix.os == 'ubuntu-latest'
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        env:
          CL_FLAGS: >-
            -Wno-unused-command-line-argument -fuse-ld=lld-link 
            /imsvc${{ github.workspace }}/xwin/crt/include 
            /imsvc${{ github.workspace }}/xwin/sdk/include/ucrt 
            /imsvc${{ github.workspace }}/xwin/sdk/include/um 
            /imsvc${{ github.workspace }}/xwin/sdk/include/shared"
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Build | Test
        run: |
          cargo llvm-cov --workspace --locked nextest
          cargo llvm-cov --locked report --codecov --output-path codecov.json
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          files: ./target/nextest/default/junit.xml
          name: me3-windows-test-results
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.os }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
        with:
          files: codecov.json
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.os }}
