on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
      - run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt install --install-recommends winehq-stable lld
          set -eux
          cargo install xwin

          xwin --accept-license splat --output "${{ github.workspace }}/xwin"
          echo "CFLAGS_x86_64_pc_windows_msvc=$CL_FLAGS" >> "$GITHUB_ENV"
          echo "CXXFLAGS_x86_64_pc_windows_msvc=$CL_FLAGS" >> "$GITHUB_ENV"
          cat > ~/.cargo/config.toml <<EOF
            [target.x86_64-pc-windows-msvc]
            linker = "lld-link"
            runner = ["env", "WINEDEBUG=-all", "wine"]
            rustflags = [
                "-Lnative=${{ github.workspace }}/xwin/crt/lib/x86_64",
                "-Lnative=${{ github.workspace }}/xwin/sdk/lib/um/x86_64",
                "-Lnative=${{ github.workspace }}/xwin/sdk/lib/ucrt/x86_64",
                "-C",
                "target-feature=+crt-static",
                "--cfg", "windows_raw_dylib",
                "--cfg", "windows_debugger_visualizer"
            ]
          EOF
        if: matrix.os == 'ubuntu-latest'
        env:
          CC_x86_64_pc_windows_msvc: clang-cl
          CXX_x86_64_pc_windows_msvc: clang-cl
          CL_FLAGS: >-
            -Wno-unused-command-line-argument -fuse-ld=lld-link 
            /imsvc${{ github.workspace }}/xwin/crt/include 
            /imsvc${{ github.workspace }}/xwin/sdk/include/ucrt 
            /imsvc${{ github.workspace }}/xwin/sdk/include/um 
            /imsvc${{ github.workspace }}/xwin/sdk/include/shared 
            /EHsc"
      - run: cargo test --all-features
