name: Delete unused caches

on:
  pull_request_target:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: snnaplab/delete-branch-cache-action@20f7992a7b8b51aa719420d11b32c9d34a5eb362 # v1.0.0
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - uses: snnaplab/delete-branch-cache-action@20f7992a7b8b51aa719420d11b32c9d34a5eb362 # v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
