on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled

name: Pull Request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-dependencies:
    name: Check dependencies
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 60
  labeler:
    name: Assign labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5

  changelog:
    runs-on: ubuntu-latest
    name: Check if CHANGELOG.md is updated
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for CHANGELOG update
        shell: bash
        run: |
          if ! git diff --name-only -r ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha}} | grep 'CHANGELOG.md'; then
              echo "Changelog needs updated"
              exit 1
          fi
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
