on:
  push:
    branches:
      - release-process

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
        with:
            cache-on-failure: true
      - run: cargo build --target x86_64-pc-windows-msvc --all --release

      - run: |
          ls target/
          ls target/release
          ls target/x86_64-pc-windows-msvc/release

      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - run: |
          echo "version=$(cargo pkgid -p me3-mod-host | cut -d '@' -f2)" >> $GITHUB_OUTPUT
        id: get_version
        shell: bash

      - name: Build installer
        run: makensis /DTARGET_DIR="${{ github.workspace }}\target\x86_64-pc-windows-msvc\release\" /DVERSION=${{ steps.get_version.outputs.version }} installer.nsi
      - name: "Upload installer"
        uses: actions/upload-artifact@v4
        with:
          name: me3-installer-${{ steps.get_version.outputs.version }}
          path: me3_installer_*.exe