on:
  release:
    types:
      - published
  push:
  workflow_dispatch:

name: Publishing
concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.name || github.ref }}
  cancel-in-progress: true

jobs:
  publish-installer:
    name: Installer
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc
      - uses: ./.github/actions/setup-windows-toolchain
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          cache-on-failure: true
      - run: |
          cargo build --target x86_64-pc-windows-msvc --all --release --features=sentry
          cargo build --target x86_64-unknown-linux-gnu -p me3-cli --release --features=sentry
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - run: |
          ls target/
          ls target/release
          ls target/x86_64-pc-windows-msvc/release

      - name: Install NSIS
        run: |
          sudo apt-get install nsis

      - run: |
          echo "version=$(cargo pkgid -p me3-mod-host | cut -d '@' -f2)" >> $GITHUB_OUTPUT
        id: get_version
        shell: bash

      - name: Build installer
        run: makensis -DTARGET_DIR="${{ github.workspace }}/target/x86_64-pc-windows-msvc/release/" -DVERSION=${{ steps.get_version.outputs.version }} installer.nsi

      - name: Upload installer
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: me3-installer-${{ steps.get_version.outputs.version }}
          path: me3_installer_*.exe

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        with:
          subject-path: |
            me3_installer_${{ steps.get_version.outputs.version }}.exe
            target/x86_64-pc-windows-msvc/release/me3_mod_host.dll
            target/x86_64-pc-windows-msvc/release/me3-launcher.exe
            target/x86_64-pc-windows-msvc/release/me3.exe
            target/x86_64-unknown-linux-gnu/release/me3

      - name: Upload installer to release
        run: >-
          gh release upload --clobber -R garyttierney/me3 ${{ github.event.release.tag_name }}
          me3_installer_${{ steps.get_version.outputs.version }}.exe
          target/x86_64-pc-windows-msvc/release/me3_mod_host.dll
          target/x86_64-pc-windows-msvc/release/me3-launcher.exe
          target/x86_64-pc-windows-msvc/release/me3.exe
          target/x86_64-unknown-linux-gnu/release/me3
        env:
          GH_TOKEN: ${{ github.token }}
        if: github.event_name == 'release'

      - name: Setup Sentry CLI
        uses: matbour/setup-sentry-cli@4cb3adf3ade6f5776a298102a9fb9e29e41bf89d # v1.3.0
        with:
          version: latest
          token: ${{ secrets.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          organization: modengine
          project: me3

      - name: Create Sentry release
        uses: getsentry/action-release@00ed2a6cc2171514e031a0f5b4b3cdc586dc171a # v3.1.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: modengine
          SENTRY_PROJECT: me3
        with:
          release: "${{ github.event.release.tag_name }}"
          finalize: "${{ !github.event.release.prerelease }}"
        if: github.event_name == 'release'

      - name: Upload debug symbols to sentry
        run: |
          sentry-cli debug-files upload --include-sources -o modengine -p me3 target/x86_64-pc-windows-msvc/release/
        if: github.event_name == 'release'
