on:
  workflow_dispatch:
  push:
    branches:
      - main
name: Create release PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.release.name || github.ref }}
  cancel-in-progress: true

jobs:
  create-release-pr:
    name: Prerelease
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@2ee2c006bbe55b0c2924d63f440aa76ecdd09aea # v2.52.3
        with:
          tool: cargo-set-version,git-cliff
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

          set +e
          # git-cliff uses GITHUB_TOKEN
          RELEASE_PUSH=1 GITHUB_TOKEN="$GH_TOKEN" ./releng/bin/create-release-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
